import { Campaign } from "@/lib/types";

export const campaigns: Campaign[] = [
  {
    id: "cmp-001",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-001",
    advertiserName: "Medalla Light",
    advertiserLogoUrl: "/logos/medalla.svg",
    adSpaceId: "space-001",
    adSpaceName: "Recomendación de Producto",
    name: "Verano Medalla 2026",
    targetKeywords: ["cerveza", "bebida", "fiesta", "playa", "verano", "happy hour"],
    targetIntents: ["product_search", "price_comparison"],
    targetChannels: ["whatsapp", "web"],
    schedule: { startDate: "2026-03-01", endDate: "2026-06-30", daysOfWeek: [0, 1, 2, 3, 4, 5, 6] },
    dailyBudgetCents: 25000,
    totalBudgetCents: 500000,
    spentCents: 187500,
    costPerImpressionCents: 15,
    priority: 85,
    messageTemplate: "¡Refréscate con {{product_name}}! Ahora a solo {{price}} en tu tienda más cercana. 🍺",
    ctaUrl: "https://shoppr.com/medalla-verano",
    creativeData: { buttonText: "Ver oferta", description: "Campaña de verano Medalla Light" },
    status: "active",
    totalImpressions: 12500,
    totalClicks: 525,
    ctr: 4.2,
    createdAt: "2026-02-25T10:00:00Z",
    updatedAt: "2026-03-22T14:00:00Z",
  },
  {
    id: "cmp-002",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-002",
    advertiserName: "Goya Foods PR",
    advertiserLogoUrl: "/logos/goya.svg",
    adSpaceId: "space-001",
    adSpaceName: "Recomendación de Producto",
    name: "Arroz Goya — Oferta Semanal",
    targetKeywords: ["arroz", "granos", "comida", "cocina", "receta", "almuerzo"],
    targetIntents: ["product_search", "general_info"],
    targetChannels: ["whatsapp"],
    schedule: { startDate: "2026-03-10", endDate: "2026-04-30" },
    dailyBudgetCents: 18000,
    totalBudgetCents: 350000,
    spentCents: 95000,
    costPerImpressionCents: 12,
    priority: 70,
    messageTemplate: "{{product_name}} de Goya — calidad premium a {{price}}. ¡Ordena ahora!",
    ctaUrl: "https://shoppr.com/goya-arroz",
    creativeData: { buttonText: "Ordenar", description: "Oferta semanal arroz Goya" },
    status: "active",
    totalImpressions: 7916,
    totalClicks: 316,
    ctr: 3.99,
    createdAt: "2026-03-08T09:00:00Z",
    updatedAt: "2026-03-22T11:00:00Z",
  },
  {
    id: "cmp-003",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-004",
    advertiserName: "Walmart PR",
    advertiserLogoUrl: "/logos/walmart.svg",
    adSpaceId: "space-001",
    adSpaceName: "Recomendación de Producto",
    name: "Rollback — Productos del Hogar",
    targetKeywords: ["limpieza", "detergente", "hogar", "ofertas", "descuento", "papel toalla"],
    targetIntents: ["product_search", "price_comparison"],
    targetChannels: ["whatsapp", "web", "telegram"],
    schedule: { startDate: "2026-03-01", endDate: "2026-03-31" },
    dailyBudgetCents: 35000,
    totalBudgetCents: 600000,
    spentCents: 420000,
    costPerImpressionCents: 10,
    priority: 90,
    messageTemplate: "¡Rollback en {{product_name}}! De ${{original_price}} a solo {{price}} en Walmart PR 🛒",
    ctaUrl: "https://shoppr.com/walmart-rollback",
    creativeData: { buttonText: "Ver en Walmart", description: "Rollback productos del hogar" },
    status: "active",
    totalImpressions: 42000,
    totalClicks: 2100,
    ctr: 5.0,
    createdAt: "2026-02-28T08:00:00Z",
    updatedAt: "2026-03-22T15:00:00Z",
  },
  {
    id: "cmp-004",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-003",
    advertiserName: "Pan Pepín",
    advertiserLogoUrl: "/logos/pepin.svg",
    adSpaceId: "space-002",
    adSpaceName: "Tip Patrocinado",
    name: "Desayuno con Pepín",
    targetKeywords: ["pan", "desayuno", "sandwich", "panadería", "mañana"],
    targetIntents: ["product_search", "general_info"],
    targetChannels: ["whatsapp"],
    schedule: { startDate: "2026-03-15", endDate: "2026-05-15", hoursOfDay: { start: 5, end: 11 } },
    dailyBudgetCents: 12000,
    totalBudgetCents: 200000,
    spentCents: 48000,
    costPerImpressionCents: 8,
    priority: 60,
    messageTemplate: "🍞 Tip: Para el mejor desayuno, prueba {{product_name}} de Pan Pepín — fresco cada mañana.",
    ctaUrl: "https://shoppr.com/pepin-desayuno",
    status: "active",
    totalImpressions: 6000,
    totalClicks: 270,
    ctr: 4.5,
    createdAt: "2026-03-14T07:00:00Z",
    updatedAt: "2026-03-22T06:00:00Z",
  },
  {
    id: "cmp-005",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-006",
    advertiserName: "Plaza Las Américas",
    advertiserLogoUrl: "/logos/plaza.svg",
    adSpaceId: "space-003",
    adSpaceName: "Mención de Marca",
    name: "Spring Sale — Plaza",
    targetKeywords: ["ropa", "moda", "zapatos", "tienda", "centro comercial", "oferta"],
    targetIntents: ["product_search", "brand_inquiry"],
    targetChannels: ["whatsapp", "web"],
    schedule: { startDate: "2026-03-20", endDate: "2026-04-15" },
    dailyBudgetCents: 20000,
    totalBudgetCents: 300000,
    spentCents: 40000,
    costPerImpressionCents: 14,
    priority: 75,
    messageTemplate: "🛍️ Spring Sale en Plaza Las Américas — hasta 50% en {{product_name}}. ¡Visítanos!",
    ctaUrl: "https://shoppr.com/plaza-spring",
    creativeData: { buttonText: "Ver ofertas", description: "Spring Sale 2026" },
    status: "active",
    totalImpressions: 2857,
    totalClicks: 114,
    ctr: 3.99,
    createdAt: "2026-03-18T10:00:00Z",
    updatedAt: "2026-03-22T12:00:00Z",
  },
  {
    id: "cmp-006",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-001",
    advertiserName: "Medalla Light",
    advertiserLogoUrl: "/logos/medalla.svg",
    adSpaceId: "space-003",
    adSpaceName: "Mención de Marca",
    name: "Medalla — Sponsor Fiestas de la Calle",
    targetKeywords: ["fiesta", "evento", "concierto", "calle", "san sebastián"],
    targetIntents: ["general_info"],
    targetChannels: ["whatsapp"],
    schedule: { startDate: "2026-01-15", endDate: "2026-01-20" },
    dailyBudgetCents: 50000,
    totalBudgetCents: 250000,
    spentCents: 250000,
    costPerImpressionCents: 18,
    priority: 95,
    messageTemplate: "🎉 Las Fiestas de la Calle con Medalla Light — {{product_name}} te espera. ¡Salud!",
    ctaUrl: "https://shoppr.com/medalla-fiestas",
    status: "completed",
    totalImpressions: 13888,
    totalClicks: 833,
    ctr: 6.0,
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-01-21T23:59:00Z",
  },
  {
    id: "cmp-007",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-005",
    advertiserName: "Econo",
    advertiserLogoUrl: "/logos/econo.svg",
    adSpaceId: "space-001",
    adSpaceName: "Recomendación de Producto",
    name: "Especiales de Cuaresma",
    targetKeywords: ["pescado", "mariscos", "cuaresma", "bacalao", "atún"],
    targetIntents: ["product_search"],
    targetChannels: ["whatsapp"],
    schedule: { startDate: "2026-03-01", endDate: "2026-04-15" },
    dailyBudgetCents: 10000,
    totalBudgetCents: 150000,
    spentCents: 72000,
    costPerImpressionCents: 9,
    priority: 55,
    messageTemplate: "🐟 Especial de Cuaresma: {{product_name}} a solo {{price}} en Econo.",
    ctaUrl: "https://shoppr.com/econo-cuaresma",
    status: "active",
    totalImpressions: 8000,
    totalClicks: 280,
    ctr: 3.5,
    createdAt: "2026-02-28T12:00:00Z",
    updatedAt: "2026-03-22T10:00:00Z",
  },
  {
    id: "cmp-008",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-008",
    advertiserName: "Oriental Bank",
    advertiserLogoUrl: "/logos/oriental.svg",
    adSpaceId: "space-002",
    adSpaceName: "Tip Patrocinado",
    name: "Ahorra con Oriental — Tips Financieros",
    targetKeywords: ["ahorro", "banco", "cuenta", "préstamo", "hipoteca", "crédito"],
    targetIntents: ["general_info", "brand_inquiry"],
    targetChannels: ["whatsapp", "web"],
    schedule: { startDate: "2026-02-01", endDate: "2026-06-30" },
    dailyBudgetCents: 15000,
    totalBudgetCents: 400000,
    spentCents: 165000,
    costPerImpressionCents: 20,
    priority: 65,
    messageTemplate: "💰 Tip financiero: Oriental Bank te ayuda con {{product_name}}. Tasa desde {{price}}%.",
    ctaUrl: "https://shoppr.com/oriental-tips",
    creativeData: { buttonText: "Conoce más", description: "Tips financieros Oriental" },
    status: "active",
    totalImpressions: 8250,
    totalClicks: 412,
    ctr: 4.99,
    createdAt: "2026-01-30T14:00:00Z",
    updatedAt: "2026-03-22T09:00:00Z",
  },
  {
    id: "cmp-009",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-010",
    advertiserName: "El Mesón Sandwiches",
    advertiserLogoUrl: "/logos/elmeson.svg",
    adSpaceId: "space-001",
    adSpaceName: "Recomendación de Producto",
    name: "Combo Almuerzo $5.99",
    targetKeywords: ["almuerzo", "sandwich", "combo", "comida rápida", "delivery"],
    targetIntents: ["product_search", "price_comparison"],
    targetChannels: ["whatsapp"],
    schedule: { startDate: "2026-03-01", endDate: "2026-04-30", hoursOfDay: { start: 10, end: 15 } },
    dailyBudgetCents: 8000,
    totalBudgetCents: 120000,
    spentCents: 56000,
    costPerImpressionCents: 7,
    priority: 50,
    messageTemplate: "🥪 Combo Almuerzo: {{product_name}} + bebida a solo {{price}} en El Mesón.",
    ctaUrl: "https://shoppr.com/elmeson-combo",
    status: "active",
    totalImpressions: 8000,
    totalClicks: 400,
    ctr: 5.0,
    createdAt: "2026-02-28T11:00:00Z",
    updatedAt: "2026-03-22T13:00:00Z",
  },
  {
    id: "cmp-010",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-004",
    advertiserName: "Walmart PR",
    advertiserLogoUrl: "/logos/walmart.svg",
    adSpaceId: "space-001",
    adSpaceName: "Recomendación de Producto",
    name: "Back to School — Walmart",
    targetKeywords: ["escuela", "cuaderno", "lápiz", "mochila", "uniforme", "útiles"],
    targetIntents: ["product_search"],
    targetChannels: ["whatsapp", "web"],
    schedule: { startDate: "2026-07-01", endDate: "2026-08-15" },
    dailyBudgetCents: 30000,
    totalBudgetCents: 500000,
    spentCents: 0,
    costPerImpressionCents: 11,
    priority: 80,
    messageTemplate: "📚 Back to School: {{product_name}} desde {{price}} en Walmart PR.",
    ctaUrl: "https://shoppr.com/walmart-bts",
    status: "draft",
    totalImpressions: 0,
    totalClicks: 0,
    ctr: 0,
    createdAt: "2026-03-20T10:00:00Z",
    updatedAt: "2026-03-20T10:00:00Z",
  },
  {
    id: "cmp-011",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-009",
    advertiserName: "Coco López",
    advertiserLogoUrl: "/logos/cocolopez.svg",
    adSpaceId: "space-002",
    adSpaceName: "Tip Patrocinado",
    name: "Piña Colada con Coco López",
    targetKeywords: ["piña colada", "coco", "bebida", "cocktail", "tropical", "receta"],
    targetIntents: ["general_info", "product_search"],
    targetChannels: ["whatsapp", "web"],
    schedule: { startDate: "2026-03-15", endDate: "2026-08-31" },
    dailyBudgetCents: 6000,
    totalBudgetCents: 100000,
    spentCents: 12000,
    costPerImpressionCents: 10,
    priority: 40,
    messageTemplate: "🥥 Receta: La Piña Colada perfecta con {{product_name}} — solo necesitas 3 ingredientes.",
    ctaUrl: "https://shoppr.com/cocolopez-receta",
    status: "active",
    totalImpressions: 1200,
    totalClicks: 60,
    ctr: 5.0,
    createdAt: "2026-03-14T15:00:00Z",
    updatedAt: "2026-03-22T08:00:00Z",
  },
  {
    id: "cmp-012",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-002",
    advertiserName: "Goya Foods PR",
    advertiserLogoUrl: "/logos/goya.svg",
    adSpaceId: "space-002",
    adSpaceName: "Tip Patrocinado",
    name: "Recetas con Goya — Habichuelas",
    targetKeywords: ["habichuelas", "frijoles", "receta", "cocina", "cena"],
    targetIntents: ["general_info"],
    targetChannels: ["whatsapp"],
    schedule: { startDate: "2026-02-01", endDate: "2026-03-15" },
    dailyBudgetCents: 10000,
    totalBudgetCents: 150000,
    spentCents: 150000,
    costPerImpressionCents: 10,
    priority: 60,
    messageTemplate: "👩‍🍳 Receta del día: Habichuelas guisadas con {{product_name}} de Goya.",
    ctaUrl: "https://shoppr.com/goya-recetas",
    status: "completed",
    totalImpressions: 15000,
    totalClicks: 600,
    ctr: 4.0,
    createdAt: "2026-01-30T09:00:00Z",
    updatedAt: "2026-03-16T00:00:00Z",
  },
  {
    id: "cmp-013",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-006",
    advertiserName: "Plaza Las Américas",
    advertiserLogoUrl: "/logos/plaza.svg",
    adSpaceId: "space-003",
    adSpaceName: "Mención de Marca",
    name: "Navidad en Plaza",
    targetKeywords: ["navidad", "regalo", "compras", "black friday", "juguete"],
    targetIntents: ["product_search", "brand_inquiry"],
    targetChannels: ["whatsapp", "web", "voice"],
    schedule: { startDate: "2025-11-15", endDate: "2025-12-31" },
    dailyBudgetCents: 40000,
    totalBudgetCents: 800000,
    spentCents: 800000,
    costPerImpressionCents: 16,
    priority: 95,
    messageTemplate: "🎄 Navidad en Plaza Las Américas — {{product_name}} con descuento especial.",
    ctaUrl: "https://shoppr.com/plaza-navidad",
    status: "completed",
    totalImpressions: 50000,
    totalClicks: 3000,
    ctr: 6.0,
    createdAt: "2025-11-10T10:00:00Z",
    updatedAt: "2026-01-02T00:00:00Z",
  },
  {
    id: "cmp-014",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-004",
    advertiserName: "Walmart PR",
    advertiserLogoUrl: "/logos/walmart.svg",
    adSpaceId: "space-002",
    adSpaceName: "Tip Patrocinado",
    name: "Tips de Ahorro — Walmart Everyday",
    targetKeywords: ["ahorro", "presupuesto", "ofertas", "barato", "económico"],
    targetIntents: ["price_comparison", "general_info"],
    targetChannels: ["whatsapp", "web"],
    schedule: { startDate: "2026-01-01", endDate: "2026-06-30" },
    dailyBudgetCents: 20000,
    totalBudgetCents: 400000,
    spentCents: 220000,
    costPerImpressionCents: 9,
    priority: 70,
    messageTemplate: "💡 Tip de ahorro: {{product_name}} más barato en Walmart PR — {{price}} vs promedio.",
    ctaUrl: "https://shoppr.com/walmart-tips",
    status: "paused",
    totalImpressions: 24444,
    totalClicks: 978,
    ctr: 4.0,
    createdAt: "2025-12-28T10:00:00Z",
    updatedAt: "2026-03-15T10:00:00Z",
  },
];
