import { Campaign } from "@/lib/types";

export const campaigns: Campaign[] = [
  {
    id: "cmp-001",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-001",
    advertiserName: "Medalla Light",
    advertiserLogoUrl: "/logos/medalla.svg",
    adSpaceId: "space-001",
    adSpaceName: "Recomendación de Producto",
    name: "Medalla Summer Fest",
    targetKeywords: ["cerveza", "bebida", "fiesta", "playa", "verano", "happy hour"],
    targetIntents: ["product_search", "price_comparison"],
    targetChannels: ["whatsapp", "web"],
    schedule: { startDate: "2026-03-01", endDate: "2026-06-30", daysOfWeek: [0, 1, 2, 3, 4, 5, 6] },
    dailyBudgetCents: 25000,
    totalBudgetCents: 500000,
    spentCents: 120000,
    costPerImpressionCents: 15,
    priority: 85,
    messageTemplate: "¡Refréscate con {{product_name}}! Ahora a solo {{price}} en tu tienda más cercana. 🍺",
    ctaUrl: "https://shoppr.com/medalla-verano",
    creativeData: { buttonText: "Ver oferta", description: "Campaña de verano Medalla Light" },
    status: "active",
    totalImpressions: 45000,
    totalClicks: 1890,
    ctr: 4.2,
    createdAt: "2026-02-25T10:00:00Z",
    updatedAt: "2026-03-22T14:00:00Z",
  },
  {
    id: "cmp-002",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-002",
    advertiserName: "Goya Foods PR",
    advertiserLogoUrl: "/logos/goya.svg",
    adSpaceId: "space-001",
    adSpaceName: "Recomendación de Producto",
    name: "Goya Recetas",
    targetKeywords: ["arroz", "granos", "comida", "cocina", "receta", "almuerzo"],
    targetIntents: ["product_search", "general_info"],
    targetChannels: ["whatsapp"],
    schedule: { startDate: "2026-03-10", endDate: "2026-04-30" },
    dailyBudgetCents: 18000,
    totalBudgetCents: 200000,
    spentCents: 85000,
    costPerImpressionCents: 12,
    priority: 70,
    messageTemplate: "{{product_name}} de Goya — calidad premium a {{price}}. ¡Ordena ahora!",
    ctaUrl: "https://shoppr.com/goya-arroz",
    creativeData: { buttonText: "Ordenar", description: "Recetas con Goya" },
    status: "active",
    totalImpressions: 32000,
    totalClicks: 1216,
    ctr: 3.8,
    createdAt: "2026-03-08T09:00:00Z",
    updatedAt: "2026-03-22T11:00:00Z",
  },
  {
    id: "cmp-003",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-004",
    advertiserName: "Walmart PR",
    advertiserLogoUrl: "/logos/walmart.svg",
    adSpaceId: "space-001",
    adSpaceName: "Recomendación de Producto",
    name: "Walmart Super Savings",
    targetKeywords: ["limpieza", "detergente", "hogar", "ofertas", "descuento", "papel toalla"],
    targetIntents: ["product_search", "price_comparison"],
    targetChannels: ["whatsapp", "web", "telegram"],
    schedule: { startDate: "2026-03-01", endDate: "2026-03-31" },
    dailyBudgetCents: 35000,
    totalBudgetCents: 150000,
    spentCents: 60000,
    costPerImpressionCents: 10,
    priority: 90,
    messageTemplate: "¡Super Savings en {{product_name}}! De ${{original_price}} a solo {{price}} en Walmart PR 🛒",
    ctaUrl: "https://shoppr.com/walmart-savings",
    creativeData: { buttonText: "Ver en Walmart", description: "Walmart Super Savings" },
    status: "paused",
    totalImpressions: 28000,
    totalClicks: 868,
    ctr: 3.1,
    createdAt: "2026-02-28T08:00:00Z",
    updatedAt: "2026-03-22T15:00:00Z",
  },
  {
    id: "cmp-004",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-005",
    advertiserName: "Supermercados Econo",
    advertiserLogoUrl: "/logos/econo.svg",
    adSpaceId: "space-001",
    adSpaceName: "Recomendación de Producto",
    name: "Econo Ofertas Hoy",
    targetKeywords: ["supermercado", "ofertas", "descuento", "compras", "ahorro"],
    targetIntents: ["product_search", "price_comparison"],
    targetChannels: ["whatsapp", "web"],
    schedule: { startDate: "2026-03-01", endDate: "2026-06-30" },
    dailyBudgetCents: 50000,
    totalBudgetCents: 1000000,
    spentCents: 200000,
    costPerImpressionCents: 10,
    priority: 88,
    messageTemplate: "🛒 Ofertas de hoy en Econo: {{product_name}} a solo {{price}}. ¡Aprovecha!",
    ctaUrl: "https://shoppr.com/econo-ofertas",
    creativeData: { buttonText: "Ver ofertas", description: "Econo Ofertas Hoy" },
    status: "active",
    totalImpressions: 50000,
    totalClicks: 2250,
    ctr: 4.5,
    createdAt: "2026-02-28T12:00:00Z",
    updatedAt: "2026-03-22T10:00:00Z",
  },
  {
    id: "cmp-005",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-006",
    advertiserName: "Plaza Las Américas",
    advertiserLogoUrl: "/logos/plaza.svg",
    adSpaceId: "space-003",
    adSpaceName: "Mención de Marca",
    name: "Plaza Moda 2024",
    targetKeywords: ["ropa", "moda", "zapatos", "tienda", "centro comercial", "oferta"],
    targetIntents: ["product_search", "brand_inquiry"],
    targetChannels: ["whatsapp", "web"],
    schedule: { startDate: "2026-04-01", endDate: "2026-05-15" },
    dailyBudgetCents: 20000,
    totalBudgetCents: 300000,
    spentCents: 0,
    costPerImpressionCents: 14,
    priority: 75,
    messageTemplate: "🛍️ Plaza Moda 2024 en Plaza Las Américas — hasta 50% en {{product_name}}. ¡Visítanos!",
    ctaUrl: "https://shoppr.com/plaza-moda",
    creativeData: { buttonText: "Ver ofertas", description: "Plaza Moda 2024" },
    status: "draft",
    totalImpressions: 0,
    totalClicks: 0,
    ctr: 0,
    createdAt: "2026-03-18T10:00:00Z",
    updatedAt: "2026-03-22T12:00:00Z",
  },
  {
    id: "cmp-006",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-007",
    advertiserName: "Triple-S",
    advertiserLogoUrl: "/logos/triples.svg",
    adSpaceId: "space-002",
    adSpaceName: "Tip Patrocinado",
    name: "Triple-S Salud",
    targetKeywords: ["salud", "seguro", "médico", "bienestar", "plan médico"],
    targetIntents: ["general_info", "brand_inquiry"],
    targetChannels: ["whatsapp", "web"],
    schedule: { startDate: "2026-01-01", endDate: "2026-03-31" },
    dailyBudgetCents: 50000,
    totalBudgetCents: 500000,
    spentCents: 500000,
    costPerImpressionCents: 18,
    priority: 95,
    messageTemplate: "🏥 Tu salud es prioridad — {{product_name}} con Triple-S. Consulta tu plan.",
    ctaUrl: "https://shoppr.com/triples-salud",
    creativeData: { buttonText: "Conoce más", description: "Triple-S Salud" },
    status: "completed",
    totalImpressions: 120000,
    totalClicks: 6240,
    ctr: 5.2,
    createdAt: "2026-01-01T10:00:00Z",
    updatedAt: "2026-03-31T23:59:00Z",
  },
  {
    id: "cmp-007",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-008",
    advertiserName: "Oriental Bank",
    advertiserLogoUrl: "/logos/oriental.svg",
    adSpaceId: "space-002",
    adSpaceName: "Tip Patrocinado",
    name: "Oriental Online",
    targetKeywords: ["ahorro", "banco", "cuenta", "préstamo", "hipoteca", "crédito"],
    targetIntents: ["general_info", "brand_inquiry"],
    targetChannels: ["whatsapp", "web"],
    schedule: { startDate: "2026-02-01", endDate: "2026-06-30" },
    dailyBudgetCents: 15000,
    totalBudgetCents: 120000,
    spentCents: 45000,
    costPerImpressionCents: 20,
    priority: 65,
    messageTemplate: "💰 Banca online con Oriental Bank — {{product_name}}. Abre tu cuenta hoy.",
    ctaUrl: "https://shoppr.com/oriental-online",
    creativeData: { buttonText: "Conoce más", description: "Oriental Online" },
    status: "active",
    totalImpressions: 18000,
    totalClicks: 630,
    ctr: 3.5,
    createdAt: "2026-01-30T14:00:00Z",
    updatedAt: "2026-03-22T09:00:00Z",
  },
  {
    id: "cmp-008",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-003",
    advertiserName: "Pan Pepín",
    advertiserLogoUrl: "/logos/pepin.svg",
    adSpaceId: "space-002",
    adSpaceName: "Tip Patrocinado",
    name: "Pan Pepín Sandwich",
    targetKeywords: ["pan", "sandwich", "desayuno", "panadería", "mañana"],
    targetIntents: ["product_search", "general_info"],
    targetChannels: ["whatsapp"],
    schedule: { startDate: "2026-03-15", endDate: "2026-05-15", hoursOfDay: { start: 5, end: 11 } },
    dailyBudgetCents: 12000,
    totalBudgetCents: 200000,
    spentCents: 55000,
    costPerImpressionCents: 8,
    priority: 60,
    messageTemplate: "🍞 El sandwich perfecto con {{product_name}} de Pan Pepín — fresco cada mañana.",
    ctaUrl: "https://shoppr.com/pepin-sandwich",
    status: "active",
    totalImpressions: 22000,
    totalClicks: 858,
    ctr: 3.9,
    createdAt: "2026-03-14T07:00:00Z",
    updatedAt: "2026-03-22T06:00:00Z",
  },
  {
    id: "cmp-009",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-004",
    advertiserName: "Walmart PR",
    advertiserLogoUrl: "/logos/walmart.svg",
    adSpaceId: "space-001",
    adSpaceName: "Recomendación de Producto",
    name: "Walmart Back to School",
    targetKeywords: ["escuela", "cuaderno", "lápiz", "mochila", "uniforme", "útiles"],
    targetIntents: ["product_search"],
    targetChannels: ["whatsapp", "web"],
    schedule: { startDate: "2026-07-01", endDate: "2026-08-15" },
    dailyBudgetCents: 30000,
    totalBudgetCents: 300000,
    spentCents: 110000,
    costPerImpressionCents: 11,
    priority: 80,
    messageTemplate: "📚 Back to School: {{product_name}} desde {{price}} en Walmart PR.",
    ctaUrl: "https://shoppr.com/walmart-bts",
    status: "paused",
    totalImpressions: 40000,
    totalClicks: 1640,
    ctr: 4.1,
    createdAt: "2026-03-20T10:00:00Z",
    updatedAt: "2026-03-20T10:00:00Z",
  },
  {
    id: "cmp-010",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-001",
    advertiserName: "Medalla Light",
    advertiserLogoUrl: "/logos/medalla.svg",
    adSpaceId: "space-003",
    adSpaceName: "Mención de Marca",
    name: "Medalla Beer Promo",
    targetKeywords: ["cerveza", "promo", "fiesta", "happy hour", "bar"],
    targetIntents: ["product_search", "general_info"],
    targetChannels: ["whatsapp"],
    schedule: { startDate: "2026-03-01", endDate: "2026-04-30" },
    dailyBudgetCents: 10000,
    totalBudgetCents: 100000,
    spentCents: 30000,
    costPerImpressionCents: 12,
    priority: 70,
    messageTemplate: "🍺 Promo Medalla: {{product_name}} a precio especial. ¡Salud!",
    ctaUrl: "https://shoppr.com/medalla-promo",
    status: "active",
    totalImpressions: 15000,
    totalClicks: 480,
    ctr: 3.2,
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-22T08:00:00Z",
  },
  {
    id: "cmp-011",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-009",
    advertiserName: "Coco López",
    advertiserLogoUrl: "/logos/cocolopez.svg",
    adSpaceId: "space-002",
    adSpaceName: "Tip Patrocinado",
    name: "Coco López Tropical Mix",
    targetKeywords: ["piña colada", "coco", "bebida", "cocktail", "tropical", "receta"],
    targetIntents: ["general_info", "product_search"],
    targetChannels: ["whatsapp", "web"],
    schedule: { startDate: "2026-03-15", endDate: "2026-08-31" },
    dailyBudgetCents: 6000,
    totalBudgetCents: 100000,
    spentCents: 12000,
    costPerImpressionCents: 10,
    priority: 40,
    messageTemplate: "🥥 Receta: La Piña Colada perfecta con {{product_name}} — solo necesitas 3 ingredientes.",
    ctaUrl: "https://shoppr.com/cocolopez-receta",
    status: "active",
    totalImpressions: 1200,
    totalClicks: 60,
    ctr: 5.0,
    createdAt: "2026-03-14T15:00:00Z",
    updatedAt: "2026-03-22T08:00:00Z",
  },
  {
    id: "cmp-012",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-002",
    advertiserName: "Goya Foods PR",
    advertiserLogoUrl: "/logos/goya.svg",
    adSpaceId: "space-002",
    adSpaceName: "Tip Patrocinado",
    name: "Goya Habichuelas Guisadas",
    targetKeywords: ["habichuelas", "frijoles", "receta", "cocina", "cena"],
    targetIntents: ["general_info"],
    targetChannels: ["whatsapp"],
    schedule: { startDate: "2026-02-01", endDate: "2026-03-15" },
    dailyBudgetCents: 10000,
    totalBudgetCents: 150000,
    spentCents: 150000,
    costPerImpressionCents: 10,
    priority: 60,
    messageTemplate: "👩‍🍳 Receta del día: Habichuelas guisadas con {{product_name}} de Goya.",
    ctaUrl: "https://shoppr.com/goya-recetas",
    status: "completed",
    totalImpressions: 15000,
    totalClicks: 600,
    ctr: 4.0,
    createdAt: "2026-01-30T09:00:00Z",
    updatedAt: "2026-03-16T00:00:00Z",
  },
  {
    id: "cmp-013",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-006",
    advertiserName: "Plaza Las Américas",
    advertiserLogoUrl: "/logos/plaza.svg",
    adSpaceId: "space-003",
    adSpaceName: "Mención de Marca",
    name: "Plaza Holiday Shopping",
    targetKeywords: ["navidad", "regalo", "compras", "black friday", "juguete"],
    targetIntents: ["product_search", "brand_inquiry"],
    targetChannels: ["whatsapp", "web", "voice"],
    schedule: { startDate: "2025-11-15", endDate: "2025-12-31" },
    dailyBudgetCents: 40000,
    totalBudgetCents: 800000,
    spentCents: 800000,
    costPerImpressionCents: 16,
    priority: 95,
    messageTemplate: "🎄 Holiday Shopping en Plaza Las Américas — {{product_name}} con descuento especial.",
    ctaUrl: "https://shoppr.com/plaza-holiday",
    status: "completed",
    totalImpressions: 50000,
    totalClicks: 3000,
    ctr: 6.0,
    createdAt: "2025-11-10T10:00:00Z",
    updatedAt: "2026-01-02T00:00:00Z",
  },
  {
    id: "cmp-014",
    tenantId: "tenant-shoppr",
    advertiserId: "adv-010",
    advertiserName: "El Mesón Sandwiches",
    advertiserLogoUrl: "/logos/elmeson.svg",
    adSpaceId: "space-001",
    adSpaceName: "Recomendación de Producto",
    name: "El Mesón Combo Express",
    targetKeywords: ["almuerzo", "sandwich", "combo", "comida rápida", "delivery"],
    targetIntents: ["product_search", "price_comparison"],
    targetChannels: ["whatsapp", "web"],
    schedule: { startDate: "2026-01-01", endDate: "2026-06-30" },
    dailyBudgetCents: 20000,
    totalBudgetCents: 250000,
    spentCents: 135000,
    costPerImpressionCents: 9,
    priority: 70,
    messageTemplate: "🥪 Combo Express: {{product_name}} + bebida a solo {{price}} en El Mesón.",
    ctaUrl: "https://shoppr.com/elmeson-express",
    status: "active",
    totalImpressions: 19500,
    totalClicks: 780,
    ctr: 4.0,
    createdAt: "2025-12-28T10:00:00Z",
    updatedAt: "2026-03-15T10:00:00Z",
  },
];
