import type { Keyword } from "@/lib/types";

export const keywords: Keyword[] = [
  { id: "kw-01", keyword: "cerveza", volume: 12400, activeCampaigns: 14, avgCpm: 320, trend: "up" },
  { id: "kw-02", keyword: "arroz", volume: 8900, activeCampaigns: 8, avgCpm: 185, trend: "stable" },
  { id: "kw-03", keyword: "pan", volume: 7200, activeCampaigns: 5, avgCpm: 140, trend: "down" },
  { id: "kw-04", keyword: "ofertas", volume: 25600, activeCampaigns: 42, avgCpm: 410, trend: "up" },
  { id: "kw-05", keyword: "seguros", volume: 4500, activeCampaigns: 12, avgCpm: 850, trend: "stable" },
  { id: "kw-06", keyword: "banco", volume: 6100, activeCampaigns: 9, avgCpm: 525, trend: "up" },
  { id: "kw-07", keyword: "café", volume: 9800, activeCampaigns: 18, avgCpm: 210, trend: "up" },
  { id: "kw-08", keyword: "pollo", volume: 11200, activeCampaigns: 7, avgCpm: 195, trend: "down" },
  { id: "kw-09", keyword: "farmacia", volume: 5400, activeCampaigns: 4, avgCpm: 350, trend: "stable" },
  { id: "kw-10", keyword: "ropa", volume: 15800, activeCampaigns: 28, avgCpm: 275, trend: "up" },
  { id: "kw-11", keyword: "electrónica", volume: 18200, activeCampaigns: 35, avgCpm: 480, trend: "up" },
  { id: "kw-12", keyword: "supermercado", volume: 22100, activeCampaigns: 51, avgCpm: 315, trend: "stable" },
  { id: "kw-13", keyword: "descuento", volume: 7650, activeCampaigns: 3, avgCpm: 16, trend: "up" },
  { id: "kw-14", keyword: "ahorro", volume: 5300, activeCampaigns: 2, avgCpm: 20, trend: "stable" },
  { id: "kw-15", keyword: "receta", volume: 3800, activeCampaigns: 2, avgCpm: 10, trend: "down" },
  { id: "kw-16", keyword: "almuerzo", volume: 4900, activeCampaigns: 1, avgCpm: 7, trend: "stable" },
  { id: "kw-17", keyword: "bebida", volume: 6100, activeCampaigns: 2, avgCpm: 13, trend: "up" },
  { id: "kw-18", keyword: "fiesta", volume: 3200, activeCampaigns: 1, avgCpm: 18, trend: "down" },
  { id: "kw-19", keyword: "playa", volume: 5500, activeCampaigns: 1, avgCpm: 15, trend: "up" },
  { id: "kw-20", keyword: "delivery", volume: 8900, activeCampaigns: 1, avgCpm: 11, trend: "up" },
  { id: "kw-21", keyword: "comida rápida", volume: 6700, activeCampaigns: 1, avgCpm: 9, trend: "stable" },
  { id: "kw-22", keyword: "piña colada", volume: 2100, activeCampaigns: 1, avgCpm: 10, trend: "up" },
  { id: "kw-23", keyword: "limpieza", volume: 3900, activeCampaigns: 1, avgCpm: 10, trend: "down" },
  { id: "kw-24", keyword: "pescado", volume: 2800, activeCampaigns: 1, avgCpm: 9, trend: "stable" },
];
